### 创建部署集群
POST {{host}}/v1/deploy_clusters
accept: application/json
Content-Type: application/json

{
  "name": "测试创建部署多机器集群",
  "machine_id_list": ["3105a55c-f57b-4549-b445-b02a85a01e7e"],
  "base_model": "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B",
  "finetune_method": "lora"
}

> {%
    // 提取响应中的Lora的ID并存储在全局变量中
    client.global.set("cluster_id", response.body.data.id);
%}

### 安装集群到服务器
POST {{host}}/v1/deploy_clusters/{{cluster_id}}/install
accept: application/json
Content-Type: application/json