### 获取GA pair 列表
GET {{host}}/v1/ga_pairs?page=1&page_size=5&file_id=91676214-10a7-4419-b6db-cd87fc97ca14

### 生成GA pair
POST {{host}}/v1/ga_pairs/generator
accept: application/json
Content-Type: application/json

{
  "file_ids": ["caf22a36-af17-4d2b-8f67-4657da3e6c64"],
  "project_id": "600bc29d-7b4c-4233-a58b-fbbb59f7f0f3",
  "append_mode": false
}

### 创建GA pair
POST {{host}}/v1/ga_pairs
accept: application/json
Content-Type: application/json

{
    "text_style": "测试",
    "text_desc": "测试描述",
    "audience": "测试归属",
    "audience_desc": "测试归属",
    "enable": true,

    "project_id": "600bc29d-7b4c-4233-a58b-fbbb59f7f0f3",
    "file_id": "91676214-10a7-4419-b6db-cd87fc97ca14"
}

> {%
    // 提取响应中的项目ID并存储在全局变量中
    client.global.set("ga_pair_id", response.body.data.id);
%}

### 获取GA pair 列表
GET {{host}}/v1/ga_pairs?page=1&page_size=5&file_id=91676214-10a7-4419-b6db-cd87fc97ca14

### 更新GA pair
PUT {{host}}/v1/ga_pairs/{{ga_pair_id}}
accept: application/json
Content-Type: application/json

{
    "text_style": "测试1",
    "text_desc": "测试描述1",
    "audience": "测试归属1",
    "audience_desc": "测试归属1",
    "enable": false,

    "project_id": "600bc29d-7b4c-4233-a58b-fbbb59f7f0f3",
    "file_id": "91676214-10a7-4419-b6db-cd87fc97ca14"
}

### 获取GA pair 列表
GET {{host}}/v1/ga_pairs?page=1&page_size=5&file_id=91676214-10a7-4419-b6db-cd87fc97ca14

### 删除GA pair
DELETE {{host}}/v1/ga_pairs/{{ga_pair_id}}
accept: application/json
Content-Type: application/json

### 获取GA pair 列表
GET {{host}}/v1/ga_pairs?page=1&page_size=5&file_id=91676214-10a7-4419-b6db-cd87fc97ca14