### 获取任务列表
GET {{host}}/v1/jobs?page=1&page_size=5&project_id=600bc29d-7b4c-4233-a58b-fbbb59f7f0f3

> {%
    // 提取响应中的项目ID并存储在全局变量中
    client.global.set("job_id", response.body.data.data[0].id);
%}

### 删除任务
DELETE {{host}}/v1/jobs/{{job_id}}

### 获取任务列表
GET {{host}}/v1/jobs?page=1&page_size=5&project_id=600bc29d-7b4c-4233-a58b-fbbb59f7f0f3

### 取消任务
POST {{host}}/v1/jobs/1/cancel