### 创建Lora
POST {{host}}/v1/lora_arguments
accept: application/json
Content-Type: application/json

{
  "additional_target": "some_module.layer1",
  "lora_alpha": 32,
  "loraplus_lr_ratio": 0.5,
  "loraplus_lr_embedding": 1e-6,
  "use_rslora": true,
  "use_dora": false,
  "pissa_init": true,
  "pissa_iter": 20,
  "pissa_convert": true,
  "create_new_adapter": true,
  "lora_dropout": 0.1,
  "lora_rank": 16,
  "lora_target": "q_proj,k_proj"
}

> {%
    // 提取响应中的Lora的ID并存储在全局变量中
    client.global.set("projectId", response.body.data.id);
%}

### 查找Lora
GET {{host}}/v1/lora_arguments/{{projectId}}

### 查找Lora（列表）
GET {{host}}/v1/lora_arguments/

### 更新Lora
PUT {{host}}/v1/lora_arguments/{{projectId}}
accept: application/json
Content-Type: application/json

{
    "lora_alpha": 3200
}

### 删除lora
DELETE {{host}}/v1/lora_arguments/{{projectId}}