### 创建机器
POST {{host}}/v1/machines
accept: application/json
Content-Type: application/json

{
  "hostname": "A30单机单卡",
  "device_type": "A30",
  "cuda_available": true,
  "gpu_count": 1,
  "ip": "118.145.90.145",
  "internal_ip": "172.31.32.2",
  "ssh_port": "22",
  "ssh_user": "root",
  "ssh_password": "123456"
}

> {%
    // 提取响应中的Machine的ID并存储在全局变量中
    client.global.set("machine_id", response.body.data.id);
%}

### 更新机器
PUT {{host}}/v1/machines/{{machine_id}}
accept: application/json
Content-Type: application/json

{
  "hostname": "gpu-node-041",
  "device_type": "A110",
  "cuda_available": true,
  "gpu_count": 1,
  "ip": "118.145.195.27",
  "internal_ip": "118.145.195.27",
  "ssh_port": "22",
  "ssh_user": "root",
  "ssh_password": "itqm123!@#"
}

### 机器列表
GET {{host}}/v1/machines?page_no=1&page_size=10

### 删除机器
DELETE {{host}}/v1/machines/{{machine_id}}

### 连接测试
POST {{host}}/v1/machines/connect_test
accept: application/json
Content-Type: application/json

{
    "ip": "118.145.195.27",
    "internal_ip": "118.145.195.27",
    "ssh_port": "22",
    "ssh_user": "root",
    "ssh_password": "itqm123!@#"
}

### 连接测试
POST {{host}}/v1/machines/connect_test
accept: application/json
Content-Type: application/json

{
  "id": "{{machine_id}}"
}