### 问题列表
GET {{host}}/v1/questions?page1&page_size=10&project_id=600bc29d-7b4c-4233-a58b-fbbb59f7f0f3

### 创建问题
POST {{host}}/v1/questions
accept: application/json
Content-Type: application/json

{
  "question": "创建新问题",
  "file_pair_id": "53559bb3-be13-4b7f-b7e3-483843e1f0eb",
  "tag_id": "70a6a473-fe6a-4e7d-8924-67d47a843187"
}

> {%
    // 提取响应中的项目ID并存储在全局变量中
    client.global.set("question_id", response.body.data.id);
%}

### 更新问题
PUT {{host}}/v1/questions/{{question_id}}
accept: application/json
Content-Type: application/json

{
  "question": "更新问题1",
  "file_pair_id": "53559bb3-be13-4b7f-b7e3-483843e1f0eb",
  "tag_id": "70a6a473-fe6a-4e7d-8924-67d47a843187"
}


### 问题生成数据集
POST {{host}}/v1/questions/dataset_generator
accept: application/json
Content-Type: application/json

{
  "project_id": "600bc29d-7b4c-4233-a58b-fbbb59f7f0f3",
  "question_ids":["14b9aba3-0704-4e7d-bccd-614813ee75f1", "277af8d7-a66f-4797-a167-3cacd5c7ca82"]
}

